### ISSUE TITLE
prototype.ino error 

### ISSUE THREAD

**Issue by KipCrossing** [thearn/Python-Arduino-Command-API#22]
Hi,
I'm getting the following error message when trying to upload the prototype.ino code via the arduino IDE:

prototype.cpp: In function ‘void setup()’:
prototype.cpp:434:13: error: no match for ‘operator!’ in ‘!Serial’
prototype.cpp:434:13: note: candidate is: operator!(bool) <built-in>

I have no C++  experience and need some help with this problem

Cheers,

KC

**Comment by KipCrossing** [comment]
It turns out you need Arduino IDE version 1.05 and the code uploads fine.

**Comment by thearn** [comment]
were you using an earlier or later version of the IDE than 1.05?
