### ISSUE TITLE
Traceback (most recent call last):   File "test.py", line 9, in <module>     board =Arduino(9600,port='/dev/ttyACM0') #plugged in via USB, serial com at rate 9600   File "/usr/local/lib/python2.7/dist-packages/arduino_python-0.2-py2.7.egg/Arduino/arduino.py", line 108, in __init__     sr = serial.Serial(port, baud, timeout=timeout) AttributeError: 'module' object has no attribute 'Serial'

### ISSUE THREAD

**Issue by lakshaygarg** [thearn/Python-Arduino-Command-API#25]

**Comment by lakshaygarg** [comment]
now I am getting this error @thearn

**Comment by thearn** [comment]
you likely need to install the serial library: `pip install pyserial`

**Comment by lakshaygarg** [comment]
I have already installed pyserial 
When I try to install it again I get
Requirement already satisfied (use --upgrade to upgrade): pyserial in /usr/local/lib/python2.7/dist-packages
Cleaning up...
Please help as I am struck @thearn
